# Generated by Django 3.2 on 2023-08-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='uid',
            new_name='member',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='uid',
            new_name='member',
        ),
        migrations.RemoveField(
            model_name='page',
            name='filepath',
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
