# Generated by Django 3.2 on 2023-08-26 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider_app', '0002_auto_20230821_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='path',
            field=models.URLField(default=''),
        ),
    ]
